package com.sapestore.controller.test;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.test.context.web.WebAppConfiguration;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import org.springframework.web.context.WebApplicationContext;

import com.sapestore.controller.BookDetailsController;
import com.sapestore.dao.BookDetailsDao;

/**
 * The class <code>AddBooksAdminControllerTest</code> contains tests for the
 * class {@link <code>AddBooksAdminController</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 7/12/14 11:05 AM
 *
 * @author kmedir
 *
 * @version $Revision$
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath:test-application-context.xml" })
@WebAppConfiguration
public class BookDetailControllerTest {
	
    private MockMvc mockMvc;

    @Autowired
    private WebApplicationContext wac;
	
	@Autowired
	private BookDetailsDao bookDetailsDao;

	/**
	 * The object that is being tested.
	 *
	 * @see com.sapestore.controller.AddBooksAdminController
	 */
	private BookDetailsController fixture = new BookDetailsController();

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public BookDetailControllerTest() {
	}

	
	/**
	 * Return the object that is being tested.
	 *
	 * @return the test fixture
	 *
	 * @see com.sapestore.controller.AddBooksAdminController
	 */
	public BookDetailsController getFixture() {
		return fixture;
	}

	/**
	 * Set the object that is being tested.
	 *
	 * @param fixture the test fixture
	 */
	public void setFixture(BookDetailsController fixture) {
		this.fixture = fixture;
	}

	/**
	 * Run the String addBooksAdmin(ModelMap) method test
	 */
	
	
	/**
	 * Run the String deleteBook(String, ModelMap, RedirectAttributes) method
	 * test
	 */
	@Test
	public void testReadAll() {
		try {
			mockMvc = MockMvcBuilders.webAppContextSetup(wac).build();
			mockMvc.perform(post("/bookDetails/readAll?isbn=9988776688"))
			.andExpect(status().isOk());
		} catch (Exception e) {
			e.printStackTrace();
		}		
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = true
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = true
 * createTestStubs = false
 * methods = addBooksAdmin(QModelMap;)
 * package = com.sapestore.controller
 * package.sourceFolder = SapeStore/src/main/java
 * superclassType = junit.framework.TestCase
 * testCase = AddBooksAdminControllerTest
 * testClassType = com.sapestore.controller.AddBooksAdminController
 */