
package com.sapestore.partner.services;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SSPartnerWebServicePortType", targetNamespace = "http://services.partner.sapestore.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SSPartnerWebServicePortType {


    /**
     * 
     * @param catId
     * @return
     *     returns java.util.List<com.sapestore.partner.services.SSPartnerBooksListBean>
     */
    @WebMethod(action = "urn:getBookList")
    @WebResult(targetNamespace = "http://services.partner.sapestore.com")
    @RequestWrapper(localName = "getBookList", targetNamespace = "http://services.partner.sapestore.com", className = "com.sapestore.partner.services.GetBookList")
    @ResponseWrapper(localName = "getBookListResponse", targetNamespace = "http://services.partner.sapestore.com", className = "com.sapestore.partner.services.GetBookListResponse")
    public List<SSPartnerBooksListBean> getBookList(
        @WebParam(name = "catId", targetNamespace = "http://services.partner.sapestore.com")
        String catId);

}
